#!/bin/bash

# Destroys postgresql instance

function print_help {
    echo "Usage: $0 app-name namespace uuid"

    echo "$0 $@" | logger -p local0.notice -t openshift_origin_postgresql_deconfigure
    exit 1
}

while getopts 'd' OPTION
do
    case $OPTION in
        d) set -x
        ;;
        ?) print_help
        ;;
    esac
done


[ $# -eq 3 ] || print_help

cartridge_type="postgresql-0.1"
source "/etc/openshift/node.conf"
source ${CARTRIDGE_BASE_PATH}/abstract/info/lib/util
source "/etc/openshift/pgsql_cartridge.conf"

setup_deconfigure "$1" $2 $3

$CART_INFO_DIR/hooks/conceal-port "$application" "$namespace" "$uuid"

if [ ! -d "$APP_HOME/app-root" ]
then
    echo "${application}.  Application directory doesn't exist:  $APP_HOME/app-root"
else
    disable_cgroups

    destroy_git_repo $application $uuid

    stop_app

    #
    # Mojo Lingo Specific Additions to DIY
    #
    PGPASSWORD=$PGSQL_CARTRIDGE_PASSWORD dropuser -h $PGSQL_CARTRIDGE_HOST -p $PGSQL_CARTRIDGE_PORT -U $PGSQL_CARTRIDGE_USER

    rm_cartridge_instance_dir "$cartridge_type"
    
    enable_cgroups
fi


#
# Remove virtualhost definition for apache
#
rm_httpd_proxy $uuid $namespace $application
